const { constants: { MINIAPP, WECHAT_MINIPROGRAM, BYTEDANCE_MICROAPP, BAIDU_SMARTPROGRAM, KUAISHOU_MINIPROGRAM }} = require('miniapp-builder-shared');

const RECURSIVE_TEMPLATE_TYPE = new Set([MINIAPP, BYTEDANCE_MICROAPP, BAIDU_SMARTPROGRAM, KUAISHOU_MINIPROGRAM ]);
const UNRECURSIVE_TEMPLATE_TYPE = new Set([WECHAT_MINIPROGRAM]);

module.exports = {
  RECURSIVE_TEMPLATE_TYPE,
  UNRECURSIVE_TEMPLATE_TYPE
};
