const { constants: { MINIAPP, WECHAT_MINIPROGRAM, BYTEDANCE_MICROAPP }} = require('miniapp-builder-shared');

const RECURSIVE_TEMPLATE_TYPE = new Set([MINIAPP]);
const UNRECURSIVE_TEMPLATE_TYPE = new Set([WECHAT_MINIPROGRAM, BYTEDANCE_MICROAPP]);

module.exports = {
  RECURSIVE_TEMPLATE_TYPE,
  UNRECURSIVE_TEMPLATE_TYPE
};
